version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-example.conf:/etc/nginx/conf.d/default.conf:ro
      - D:/secrets/tralya-certs:/etc/ssl/private:ro
    restart: always

  hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: hbbs
    command: hbbs -r 0.0.0.0:21117
    ports:
      - "31115:21115/tcp"
      - "31116:21116/tcp"
      - "31116:21116/udp"
      - "31117:21117/tcp"
      - "31117:21117/udp"
    restart: always

  hbbr:
    image: rustdesk/rustdesk-server:latest
    container_name: hbbr
    command: hbbr -k /etc/ssl/private/tralya.com.key
    volumes:
      - D:/secrets/tralya-certs:/etc/ssl/private:ro
    restart: always
